name: Fetch Weather Data and Deploy to Pages

on:
  schedule:
    # Runs every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch: # Allows manual triggering

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # URL will be shown in Actions summary

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Use a recent Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch weather data
        env:
          WF_TOKEN: ${{ secrets.WF_TOKEN }} # Use the secret token
        run: python fetch_weather.py

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the specific data file to the root directory of the Pages site
          path: ./weather_data.json

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # No build step needed as we are deploying a single static file
